car_loader_memory=200000			# Memory allocated for loading car models (default: 80000)
vehicle_count=512					# Amount of vehicles (default: 20)
collision_dispatcher=4096			# default: 256

[slot_pools]
AnimCtrlSlotPool=170				# default: 170
Anim_CAnimSkeleton_SlotPool=8		# default: 8
Anim_CNFSAnimBank_SlotPool=81		# default: 81
AStarSearchRequestSlotPool=16		# default: 16
AUD_Csis_SlotPools=256				# default: 256
bFile_System=192					# default: 192
CarEmitterPositionSlotPool=300		# default: 300
CarLoadedRideInfoSlotPool=1024		# default: 24
CarLoadedSkinLayerSlotPool=38400	# default: 900
CarLoadedSolidPackSlotPool=1536		# default: 36
CarLoadedTexturePackSlotPool=1536	# default: 36
CarPartModelPool=43690				# default: 1024
ClanSlotPool=40						# default: 40
CustomizationLightMaterialPool=512	# default: 512
DynamicSurface=64					# default: 64
eAnimTextureSlotPool=256			# default: 256
eMeshRender=4096					# default: 4096
EventHandlerSlotPool=20				# default: 20
EventSlotPool=60					# default: 60
FERenderObjectSlotPool=384			# default: 384
FERenderPolySlotPool=840			# default: 840
LoadedVinylLayersSlotPool=40960		# default: 960
QueuedFileSlotPool=250				# default: 250
ResourceFileSlotPool=80				# default: 80
ScheduledSpeechEvent_slotpool=200	# default: 200
SkidSetSlotPool=128					# default: 128
SpaceNodeSlotPool=240				# default: 240
SpeechSampleData_slotpool=500		# default: 500
VehicleDamagePartSlotPool=10240		# default: 240
VehiclePartDamageZoneSlotPool=4300	# default: 100
VoiceActors_slotpool=20				# default: 20
WorldAnimCtrl_SlootPol=512			# default: 512
WorldModelSlotPool=256				# default: 256